version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native TCP interface
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_DB: default
      CLICKHOUSE_PASSWORD: "ch_password"

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./custom_my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the seed data script

  # Golang-based load generator for MySQL CRUD operations
  crud_load_gen:
    build: ../mysql2kafka/loadgen
    depends_on:
      - mysql
    restart: on-failure 
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: mydb

  transfer:
    build: ../.. # build main transfer docker CLI
    command:
      - replicate
      - --transfer
      - /usr/local/bin/transfer.yaml
      - --log-level
      - info
    depends_on:
      - mysql
      - clickhouse
    restart: on-failure 
    volumes:
      - ./transfer.yaml:/usr/local/bin/transfer.yaml
